version: "3.9"

services:
  # 1. DATABASE SERVICE
  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${DB_LOCAL_PORT}:${DB_DOCKER_PORT}"  # Map 14331:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    command: [
      "--character-set-server=utf8",
      "--collation-server=utf8_general_ci",
      "--init-connect=SET NAMES utf8"
    ]

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. BACKEND SERVICE
  be_minizaloapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be_minizaloapp
    restart: always
    depends_on:
      mysql_db:
        condition: service_healthy
    env_file:
      - .env

    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:${DB_DOCKER_PORT}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

    ports:
      - "${APP_PORT}:8080"
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge