version: '3.8'

services:
  # Dịch vụ MySQL
  db_agrishrimp:
    image: mysql:8.0
    container_name: mysql_agrishrimp
    restart: always
    environment:
      MYSQL_DATABASE: agri_shrimp_db
      MYSQL_ROOT_PASSWORD: your_password_here
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Dịch vụ Redis
  redis_agrishrimp:
    image: redis:alpine
    container_name: redis_agrishrimp
    restart: always
    ports:
      - "6379:6379"

  # Dịch vụ Backend Spring Boot
  be_agrishrimp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_agrishrimp
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - db_agrishrimp
      - redis_agrishrimp
    environment:
      # Ghi đè cấu hình để Backend gọi đúng tên Container thay vì localhost
      DBMS_CONNECTION: jdbc:mysql://db_agrishrimp:3306/agri_shrimp_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      DBMS_USERNAME: root
      DBMS_PASSWORD: your_password_here
      SPRING_DATA_REDIS_HOST: redis_agrishrimp

volumes:
  mysql_data: