# ==================================================
# APPLICATION CONFIG - BASE (COMMON FOR ALL ENV)
# --------------------------------------------------
# File cau hinh CHUNG cho toan bo he thong
#
# Dung cho:
# - Cau hinh khong phu thuoc moi truong
# - Khong chua thong tin DB, password
#
# Cac file moi truong:
# - application-dev.properties  (local / dev)
# - application-prod.properties (server that)
# ==================================================

# ======================
# APPLICATION
# ======================
spring.application.name=agrishrimp-be
spring.profiles.active=dev

# Social API URLs
social.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
social.facebook.user-info-uri=https://graph.facebook.com/me


# Captcha Configuration
# QUAN TR?NG: Thi?u dòng này thì AuthService s? l?i khi g?i Google

google.recaptcha.verify.url=https://www.google.com/recaptcha/api/siteverify

# Captcha Secret (Ví d? Google Recaptcha)
recaptcha.secret-key=6LfJsjcsAAAAAPsVQHCZcjkeq7FNi_QtxA_hdofb