# ==================================================
# APPLICATION CONFIG - BASE (COMMON FOR ALL ENV)
# --------------------------------------------------
# File c?u hình CHUNG cho toàn b? h? th?ng
#
# Dùng cho:
# - C?u hình không ph? thu?c môi tr??ng
# - Không ch?a thông tin DB, password
#
# Các file môi tr??ng:
# - application-dev.properties  (local / dev)
# - application-prod.properties (server th?t)
# ==================================================

# ======================
# APPLICATION
# ======================
spring.application.name=agrishrimp-be


