# ==================================================
# APPLICATION CONFIG - PRODUCTION ENVIRONMENT
# --------------------------------------------------
# Moi truong: Production (server that)
#
# QUY DINH BAT BUOC:
# 1. KHONG hardcode username / password DB
# 2. KHONG chinh DB bang tay tren server
# 3. Moi thay doi DB phai thong qua Flyway
# 4. Thong tin nhay cam lay tu ENV VARIABLES
#
# File nay chi chua CAU TRUC, KHONG chua bi mat
# ==================================================

spring.application.name=agrishrimp-be