logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO

spring:
  main:
    lazy-initialization: true

  data:
    redis:
      repositories:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

app:
  startup:
    schema-patches:
      enabled: false
    seed-data:
      enabled: false
